- database/__init__.py
- database/repositories.py
- included/ModuleTemplate.py
- included/modules/DNSRecon.py
- included/modules/Fierce.py
- included/modules/GobusterDNS.py
- included/modules/GobusterDir.py
- included/modules/Ingestor.py
- included/modules/Nmap.py
- included/modules/Sublist3r.py
- included/modules/TheHarvester.py
- included/reports/CidrReport.py
- included/reports/ScopeReport.py
- included/utilities/color_display.py
- included/utilities/formatting.py
Made major changes to how scoping works and how Ingestor works.
> Scoping revamp

- included/ModuleTemplate.py
- included/modules/Subfinder.py
Created a module for Subfinder.
> Added the basis for the Subfinder module.

- .github/issue_template.md
- .github/pull_request_template.md
Add an issue and pull request template.
> Add github templates.

- armory/database/repositories.py
Fixes #`16`
- line 320 - if "nets" in res.keys():
- line 330 - res = {'nets': [{'cidr': '0.0.0.0/0', 'description': 'Whois failed to resolve.'}]}
> fixed if and dict for null whoami

- armory/included/modules/Masscan.py
> Add a Masscan module

- armory/included/modules/Whois.py
- armory/included/utilities/readFile.py
Fixes encoding issues when handling non utf-8 within Whois data.
> Added Encoding Execption Handling

- Pipfile
- armory/database/repositories.py
- armory/included/modules/Ingestor.py
- armory/included/utilities/get_domain_ip.py
- setup.py
- Updates get_domain_ip utility to use socket DNS resolution if dns.resolver does not work
- Updates repositories.py to use utility script
> Support for Local DNS Resolution (hosts file) 

- Pipfile
- Pipfile.lock
- armory/shell.py
- setup.py
- Adds color to the `armory-shell` banner.
> Colorize shell

- armory/included/modules/Nmap.py
(cherry picked from commit 79354574cf7f45216a4d828aacc373963cae9752)
> Fixed an issue when printing an error.

- armory2/armory2/urls.py
- armory2/armory_main/included/modules/Gowitness.py
- armory2/armory_main/included/modules/ShodanImport.py
- armory2/armory_main/included/utilities/validate_ip.py
- armory2/armory_main/models/network.py
- armory2/armory_main/templates/domain_scoping/basedomain.html
- armory2/armory_main/templates/domain_scoping/domains.html
- armory2/armory_main/templates/domain_scoping/index.html
- armory2/armory_main/templates/domain_scoping/ips.html
- armory2/armory_main/templates/scoping/cidr.html
- armory2/armory_main/urls/domain_scoping_urls.py
- armory2/armory_main/views/domain_scoping_views.py
- docker/Dockerfile
> Domainscoping

- armory2/armory_main/included/modules/Ingestor.py
Instead of getting all of the IPAddresses using `.filter` it was using `.get` which is expecting only one object to be returned on line 309.
Black also ran against the code and changed the format.
> Fix an issue with the descope CIDR.

- armory2/armory_main/included/modules/Nessus.py
- docker/Dockerfile
Fixed some import errors due to Nessus being funky.
> Nessus fix

- armory2/armory_cmd.py
- armory2/armory_main/included/ModuleTemplate.py
- armory2/armory_main/included/modules/FFuF.py
Fixed various issues with command line options.
> Fixed two main issues with command line options:

- armory2/armory_main/included/utilities/header_tools.py
Fixed indentation on line 37. Only first header was getting appended to `new_headers` dict and getting incorrect results when generating header findings.
> Fix indentation

- armory2/armory_main/included/utilities/header_tools.py
Cleans up issues with header_scanner and helps with url redirections. Added a default firefox user agent to the get request
> added user_agent header to header_tools to help with url redirections

- armory2/armory_main/included/modules/Xsscrapy.py
- armory2/armory_main/included/utilities/get_urls.py
- armory2/armory_main/included/webapps/host_summary/templates/host_summary/host_summary_data.html
- armory2/armory_main/included/webapps/host_summary/templates/host_summary/xsscrapy.html
- armory2/armory_main/included/webapps/host_summary/urls.py
- armory2/armory_main/included/webapps/host_summary/views.py
Added Xsscrapy to Host Summary webapp.
> Host summary xsscrapy

- armory2/armory_main/included/modules/XSStrike.py
- armory2/armory_main/included/webapps/host_summary/templates/host_summary/host_summary_data.html
- armory2/armory_main/included/webapps/host_summary/templates/host_summary/xsstrike.html
- armory2/armory_main/included/webapps/host_summary/urls.py
- armory2/armory_main/included/webapps/host_summary/views.py
Added in XSStrike (tool and host summary module)
> Host summary xsstrike

- armory2/armory_main/included/modules/Nessus.py
- armory2/armory_main/included/utilities/nessus.py
> Added ability to poll nessus folder and launch jobs as other jobs finish

- requirements.txt
This is to revert selenium, and maintain SSLv2 and v3 support.
> Revert selenium

- armory2/armory_main/included/utilities/nmap.py
> Fixed bug in nmap

- armory2/armory_main/included/webapps/host_summary/templates/host_summary/host_summary_data.html
- armory2/armory_main/models/network.py
> Fix for displaying virtualhosts in host summary

- armory2/armory_main/included/modules/Gowitness.py
> Updated since gowitness base output db string needs sqlite:// now.

- armory2/armory_main/included/modules/Gowitness.py
> Another fix

- armory2/armory_main/included/modules/Whois.py
> Fixed whois importing results

- armory2/armory_main/included/ModuleTemplate.py
- armory2/armory_main/included/modules/FFuF.py
- armory2/armory_main/included/modules/Nikto.py
- armory2/armory_main/included/modules/VirtHostScanner.py
- armory2/armory_main/included/modules/Whois.py
Fixes a bug in whois module that wasn't grabbing the correct CIDRs
Adds a --delay option to the ToolModule base template that can be used to institute a delay between requests
> Fixed bug with whois, and added ability to have delays between commands.

- armory2/armory_main/included/ModuleTemplate.py
- armory2/armory_main/included/modules/Whois.py
> Fixed a bug with the delay, and whois

- armory2/armory_main/included/modules/Whois.py
> Removed the last bits of delay
